# Generated by Django 5.2.7 on 2025-10-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('total_households', models.IntegerField()),
                ('total_persondays', models.IntegerField()),
                ('women_participation', models.FloatField()),
                ('total_expenditure', models.FloatField()),
                ('wages_paid', models.FloatField()),
            ],
        ),
    ]
